### ISSUE TITLE
Can't compile latex on codespaces

### ISSUE THREAD

**Issue by PaoloPenazzi** [FilippoVissani/latex-template#2]
I can't compile latex reports on the codespace. Is this the intended behaviour? I thought the codespace would be ready to compile latex without doing extra steps.

steps to reproduce:
- create a new codespace
- try to compile thesis-main.tex

**Comment by FilippoVissani** [comment]
I created a new Codespace, and I was able to compile the template without problems.
Can you tell me how you tried to compile the template?

**Comment by FilippoVissani** [comment]
I was able to replicate the problem using VS Code web.
The extension latex-workshop used to compile latex is not loaded correctly, I think this is related to this James-Yu/LaTeX-Workshop#469 and this James-Yu/LaTeX-Workshop#474

**Comment by PaoloPenazzi** [comment]
Ok so it's up to the extension owner to fix this. Thanks
